apiVersion: v1
kind: Service
metadata:
  name: quote-api-service
spec:
  type: NodePort
  selector:
    app: quote-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30007

